# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa862a6b755e5dcb19d53518778caa1d41402cf963d87a8ca53560853ca5d0928e470e76aa4e55e34e058eb9a131ab480735f8aa3c94d1b7137f820bc6e9d180

test:
  secret_key_base: daa1a7d5c03b9270e2a52517fc9e2a7102b904e1230fea4a2691e11c1df325d1ad6c87962fe87b45458b40972de3cd77a0855783d6097b0b5ab28aa618880ee9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
